name: e2e test for Android
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ledgerhq/actions/check-member@v1.0.0
        with:
          username: ${{ github.actor }}
          ban: ledgerlive

      - uses: actions/checkout@v2

      # - uses: actions/setup-node@master
      #   with:
      #     node-version: 12.x

      # - name: Get yarn cache
      #   id: yarn-cache
      #   run: echo "::set-output name=dir::$(yarn cache dir)"

      # - uses: actions/cache@v1
      #   with:
      #     path: ${{ steps.yarn-cache.outputs.dir }}
      #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-yarn-

      # - name: Install dependencies
      #   run: yarn

      # - name: Install applesimutils
      #   run: |
      #     brew tap wix/brew
      #     brew install applesimutils

      # - name: Build
      #   run: yarn e2e:build -c android.staging

      # - name: Test
      #   run: yarn e2e:test -c android.staging

      - name: List pre installed emulators
        run: "$ANDROID_HOME"/emulator/emulator -list-avds
