name: e2e test for Android
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: List pre installed emulators
        run: "$ANDROID_HOME"/emulator/emulator -list-avds
